name: create-release

on:
  workflow_dispatch

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set release name
        id: release_name
        run: echo "release_name=release-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: actions/download-artifact@v4
        with:
          # when name is not specified, all artifacts from this run will be downloaded
          path: artifacts

      - name: Compress artifacts
        run: |
          mkdir release
          pushd artifacts
          tar --format=ustar -czf ../release/dawn-windows-x64.tar.gz dawn-windows-x64
          tar --format=ustar -czf ../release/dawn-mac-x64.tar.gz dawn-mac-x64
          tar --format=ustar -czf ../release/dawn-mac-arm64.tar.gz dawn-mac-arm64

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release/*"
          tag: ${{ steps.release_name.outputs.release_name }}
